// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TellerDB;

#nullable disable

namespace TellerDB.Migrations
{
    [DbContext(typeof(BankContext))]
    partial class BankContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TellerDB.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountId"));

                    b.Property<int>("AccountNumber")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<int>("AccountType")
                        .HasColumnType("int");

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.HasKey("AccountId");

                    b.HasIndex("MemberId");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            AccountId = 1,
                            AccountNumber = 1,
                            AccountType = 1,
                            Balance = 500.00m,
                            IsActive = true,
                            MemberId = 1
                        },
                        new
                        {
                            AccountId = 2,
                            AccountNumber = 1,
                            AccountType = 2,
                            Balance = 1000.00m,
                            IsActive = true,
                            MemberId = 1
                        },
                        new
                        {
                            AccountId = 3,
                            AccountNumber = 2,
                            AccountType = 1,
                            Balance = 5000.00m,
                            IsActive = true,
                            MemberId = 2
                        },
                        new
                        {
                            AccountId = 4,
                            AccountNumber = 3,
                            AccountType = 1,
                            Balance = 1500.00m,
                            IsActive = true,
                            MemberId = 3
                        });
                });

            modelBuilder.Entity("TellerDB.Address", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AddressId"));

                    b.Property<int>("AccountNumber")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Street1")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Street2")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ZipCode")
                        .HasColumnType("int");

                    b.Property<int?>("ZipPlusFour")
                        .HasColumnType("int");

                    b.HasKey("AddressId");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            AddressId = 1,
                            AccountNumber = 1,
                            City = "Indianapolis",
                            IsActive = true,
                            State = "IN",
                            Street1 = "123 Main St",
                            ZipCode = 46201
                        },
                        new
                        {
                            AddressId = 2,
                            AccountNumber = 2,
                            City = "New York",
                            IsActive = true,
                            State = "IN",
                            Street1 = "456 Elm St",
                            ZipCode = 46038
                        },
                        new
                        {
                            AddressId = 3,
                            AccountNumber = 3,
                            City = "Los Angeles",
                            IsActive = true,
                            State = "IN",
                            Street1 = "789 Oak St",
                            ZipCode = 29572
                        });
                });

            modelBuilder.Entity("TellerDB.Member", b =>
                {
                    b.Property<int>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MemberId"));

                    b.Property<int>("AccountNumber")
                        .HasColumnType("int");

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MemberId");

                    b.HasIndex("AddressId");

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            MemberId = 1,
                            AccountNumber = 1,
                            AddressId = 1,
                            FirstName = "John",
                            IsActive = true,
                            LastName = "Doe"
                        },
                        new
                        {
                            MemberId = 2,
                            AccountNumber = 2,
                            AddressId = 2,
                            FirstName = "Jane",
                            IsActive = true,
                            LastName = "Smith"
                        },
                        new
                        {
                            MemberId = 3,
                            AccountNumber = 3,
                            AddressId = 3,
                            FirstName = "Super",
                            IsActive = true,
                            LastName = "Man"
                        });
                });

            modelBuilder.Entity("TellerDB.Account", b =>
                {
                    b.HasOne("TellerDB.Member", "Member")
                        .WithMany("Accounts")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("TellerDB.Member", b =>
                {
                    b.HasOne("TellerDB.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("TellerDB.Member", b =>
                {
                    b.Navigation("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
